package utng.pcamacho.model.pojos;
// Generated 6/12/2017 11:09:14 AM by Hibernate Tools 4.3.1



/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer id;
     private String titulo;
     private String autor;
     private String editorial;
     private String edicion;

    public Libros() {
    }

    public Libros(String titulo, String autor, String editorial, String edicion) {
       this.titulo = titulo;
       this.autor = autor;
       this.editorial = editorial;
       this.edicion = edicion;
    }

    public Libros(Integer id, String titulo, String autor, String editorial, String edicion) {
        this.id = id;
        this.titulo = titulo;
        this.autor = autor;
        this.editorial = editorial;
        this.edicion = edicion;
    }
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(String edicion) {
        this.edicion = edicion;
    }




}


